[package]
name = "list_files"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
polars = "0.18.0"
polars-core = "0.18.0"
xlsxwriter = "0.3.5"